extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_f3dlite_material_001_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_002_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_003_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_lights;
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[299];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_002_mesh_layer_1_vtx_0[378];
extern Gfx castle_grounds_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_001_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_002_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_5[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
