extern void scroll_Goombaplatform_offset_000_mesh_layer_1_vtx_0();
extern void scroll_Goombaplatform_offset_000_mesh_layer_1_vtx_1();
extern void scroll_Goombaplatform_offset_000_001_mesh_layer_1_vtx_0();
extern void scroll_Goombaplatform_offset_000_001_mesh_layer_1_vtx_2();
extern void scroll_Goombaplatform_offset_000_002_mesh_layer_1_vtx_0();
extern void scroll_Goombaplatform_offset_000_003_mesh_layer_1_vtx_0();
extern void scroll_actor_geo_Goombaplatform();
