extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const MacroObject bits_area_1_macro_objs[];
extern Lights1 bits_dl_f3dlite_material_lights;
extern Lights1 bits_dl_f3dlite_material_003_lights;
extern Lights1 bits_dl_f3dlite_material_004_lights;
extern Lights1 bits_dl_f3dlite_material_008_lights;
extern Lights1 bits_dl_f3dlite_material_001_lights;
extern Lights1 bits_dl_f3dlite_material_002_lights;
extern u8 bits_dl_tentmix_ci8[];
extern u8 bits_dl_tentmix_ci8_pal_rgba16[];
extern u8 bits_dl_crystalA_rgba16[];
extern Vtx bits_dl_Circle_mesh_layer_1_vtx_0[190];
extern Gfx bits_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cube_mesh_layer_1_vtx_0[863];
extern Gfx bits_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cube_mesh_layer_1_vtx_1[48];
extern Gfx bits_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bits_dl_Cube_mesh_layer_1_vtx_2[48];
extern Gfx bits_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bits_dl_Cube_mesh_layer_5_vtx_0[8];
extern Gfx bits_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx bits_dl_Plane_mesh_layer_4_vtx_0[4];
extern Gfx bits_dl_Plane_mesh_layer_4_tri_0[];
extern Vtx bits_dl_Plane_001_mesh_layer_4_vtx_0[4];
extern Gfx bits_dl_Plane_001_mesh_layer_4_tri_0[];
extern Gfx mat_bits_dl_MessedUpTexture[];
extern Gfx mat_revert_bits_dl_MessedUpTexture[];
extern Gfx mat_bits_dl_f3dlite_material[];
extern Gfx mat_bits_dl_f3dlite_material_003[];
extern Gfx mat_bits_dl_f3dlite_material_004[];
extern Gfx mat_revert_bits_dl_f3dlite_material_004[];
extern Gfx mat_bits_dl_f3dlite_material_008[];
extern Gfx mat_bits_dl_f3dlite_material_001[];
extern Gfx mat_bits_dl_f3dlite_material_002[];
extern Gfx bits_dl_Circle_mesh_layer_1[];
extern Gfx bits_dl_Cube_mesh_layer_1[];
extern Gfx bits_dl_Cube_mesh_layer_5[];
extern Gfx bits_dl_Plane_mesh_layer_4[];
extern Gfx bits_dl_Plane_001_mesh_layer_4[];
extern Gfx bits_dl_material_revert_render_settings[];
