extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern Lights1 bob_dl_sm64_material_001_lights;
extern Lights1 bob_dl_skin_lights;
extern Lights1 bob_dl_Clothb_layer1_area1_lights;
extern Lights1 bob_dl_clothA_lights;
extern Lights1 bob_dl_f3dlite_material_004_lights;
extern Lights1 bob_dl_f3dlite_material_lights;
extern u8 bob_dl_tent2_ci4[];
extern u8 bob_dl_tent2_ci4_pal_rgba16[];
extern u8 bob_dl_Crosses_i8[];
extern Vtx bob_dl_Building_mesh_layer_1_vtx_0[332];
extern Gfx bob_dl_Building_mesh_layer_1_tri_0[];
extern Vtx bob_dl_FappyStatue_mesh_layer_1_vtx_0[342];
extern Gfx bob_dl_FappyStatue_mesh_layer_1_tri_0[];
extern Vtx bob_dl_FappyStatue_mesh_layer_1_vtx_1[94];
extern Gfx bob_dl_FappyStatue_mesh_layer_1_tri_1[];
extern Vtx bob_dl_FappyStatue_mesh_layer_1_vtx_2[141];
extern Gfx bob_dl_FappyStatue_mesh_layer_1_tri_2[];
extern Vtx bob_dl_FappyStatue_mesh_layer_1_vtx_3[32];
extern Gfx bob_dl_FappyStatue_mesh_layer_1_tri_3[];
extern Vtx bob_dl_QuestionRoomTemplate_mesh_layer_1_vtx_0[20];
extern Gfx bob_dl_QuestionRoomTemplate_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_sm64_material_001[];
extern Gfx mat_bob_dl_skin[];
extern Gfx mat_bob_dl_Clothb_layer1_area1[];
extern Gfx mat_revert_bob_dl_Clothb_layer1_area1[];
extern Gfx mat_bob_dl_clothA[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx bob_dl_Building_mesh_layer_1[];
extern Gfx bob_dl_FappyStatue_mesh_layer_1[];
extern Gfx bob_dl_QuestionRoomTemplate_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
