extern const GeoLayout bitdw_area_1_geo[];
extern const GeoLayout bitdw_area_1[];
extern const Collision bitdw_area_1_collision[];
extern const MacroObject bitdw_area_1_macro_objs[];
extern Lights1 bitdw_dl_f3dlite_material_lights;
extern Vtx bitdw_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bitdw_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_bitdw_dl_f3dlite_material[];
extern Gfx bitdw_dl_Cube_mesh_layer_1[];
extern Gfx bitdw_dl_material_revert_render_settings[];
