extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_lights;
extern Lights1 wf_dl_TentB_lights;
extern Lights1 wf_dl_TentA_lights;
extern Lights1 wf_dl_Temp4vision_lights;
extern u8 wf_dl_TentWhiteDark_ci4[];
extern u8 wf_dl_TentWhiteDark_ci4_pal_rgba16[];
extern u8 wf_dl_TentPurpleDark_ci4[];
extern u8 wf_dl_TentPurpleDark_ci4_pal_rgba16[];
extern Vtx wf_dl_Approximate_Scaffold_Height_Maybe_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Approximate_Scaffold_Height_Maybe_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Main_mesh_layer_1_vtx_0[258];
extern Gfx wf_dl_Main_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Main_mesh_layer_1_vtx_1[296];
extern Gfx wf_dl_Main_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Main_mesh_layer_1_vtx_2[535];
extern Gfx wf_dl_Main_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Scaffolding_mesh_layer_1_vtx_0[144];
extern Gfx wf_dl_Scaffolding_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_TentB[];
extern Gfx mat_revert_wf_dl_TentB[];
extern Gfx mat_wf_dl_TentA[];
extern Gfx mat_revert_wf_dl_TentA[];
extern Gfx mat_wf_dl_Temp4vision[];
extern Gfx wf_dl_Approximate_Scaffold_Height_Maybe_mesh_layer_1[];
extern Gfx wf_dl_Main_mesh_layer_1[];
extern Gfx wf_dl_Scaffolding_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
