extern const GeoLayout bowser_3_area_1_geo[];
extern const GeoLayout bowser_3_area_1[];
extern const Collision bowser_3_area_1_collision[];
extern const MacroObject bowser_3_area_1_macro_objs[];
extern Lights1 bowser_3_dl_f3dlite_material_lights;
extern Lights1 bowser_3_dl_f3dlite_material_001_lights;
extern Lights1 bowser_3_dl_f3dlite_material_002_lights;
extern u8 bowser_3_dl_tentmix_ci8[];
extern u8 bowser_3_dl_tentmix_ci8_pal_rgba16[];
extern Vtx bowser_3_dl_Circle_mesh_layer_1_vtx_0[122];
extern Gfx bowser_3_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bowser_3_dl_Cube_mesh_layer_1_vtx_0[162];
extern Gfx bowser_3_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bowser_3_dl_Plane_mesh_layer_4_vtx_0[4];
extern Gfx bowser_3_dl_Plane_mesh_layer_4_tri_0[];
extern Vtx bowser_3_dl_Plane_001_mesh_layer_4_vtx_0[4];
extern Gfx bowser_3_dl_Plane_001_mesh_layer_4_tri_0[];
extern Gfx mat_bowser_3_dl_MessedUpTexture[];
extern Gfx mat_revert_bowser_3_dl_MessedUpTexture[];
extern Gfx mat_bowser_3_dl_f3dlite_material[];
extern Gfx mat_bowser_3_dl_f3dlite_material_001[];
extern Gfx mat_bowser_3_dl_f3dlite_material_002[];
extern Gfx bowser_3_dl_Circle_mesh_layer_1[];
extern Gfx bowser_3_dl_Cube_mesh_layer_1[];
extern Gfx bowser_3_dl_Plane_mesh_layer_4[];
extern Gfx bowser_3_dl_Plane_001_mesh_layer_4[];
extern Gfx bowser_3_dl_material_revert_render_settings[];
